bench *test='':
    cargo criterion --plotting-backend disabled --output-format quiet -- {{test}}

stat test='':
    cargo build --profile bench --benches
    perf stat cargo criterion -- --profile-time 4 {{test}}

stat-selection test='':
    cargo build --profile bench --benches
    perf stat -e task-clock,cycles,instructions,branches,branch-misses cargo criterion -- --profile-time 4 {{test}}

perf test='':
    cargo build --profile bench --benches
    perf record cargo criterion -- --profile-time 4 {{test}}
    perf report

perf-misses test='':
    cargo build --profile bench --benches
    perf record -e branch-misses cargo criterion -- --profile-time 4 {{test}}
    perf report

flame test='':
    cargo build --profile bench --benches
    cargo flamegraph --bench bench --open -- --bench --profile-time 4 {{test}}
